# Naziv servisa
spring.application.name=grid-actuator

# Port na kome radi mikroservis
server.port=8081

# Podaci za POSTGRESQL bazu
spring.datasource.url=jdbc:postgresql://localhost:5432/voltgraph_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Konfiguracija Hibernate (auto update - dodaje, prikaz SQL u konzoli)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Drugi servisi ce proveravati da li je actuator pokrenut
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator