spring.application.name=grid-controller
server.port=8083

services.grid-actuator.url=http://localhost:8081

orchestrator.balance-interval=1000
controller.imbalance-threshold=5.0
controller.max-battery-power=50.0

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

logging.level.root=INFO
logging.level.rs.ac.bg.fon.marko.grid.controller=DEBUG
logging.level.feign=DEBUG